apiVersion: ENC[AES256_GCM,data:BP8=,iv:FJWMxcHZ2eraY4zkgGeXoIEjuAeX9kSBq9rdw7sZJwU=,tag:ZgjqSpxJwEGhH/Z4afjRAg==,type:str]
data:
    token: ENC[AES256_GCM,data:LBGoPiF2GKIcMbLF67Urhy7YUZ58pqLWbtwysvx2t+Lco4H2DvyPFifY+J+ZcZtYCKF8MR4RmywD+VV3nNLLrY/FlSPmg7r8mBL+Rg==,iv:dc15UoL8cnxWSJSWjOijDsSTHfNYrseXxG0WEm4YVNw=,tag:ajyMG3gpDJ7C7hYn+GiVdA==,type:str]
kind: ENC[AES256_GCM,data:WIg+oW/i,iv:STogk3jdjzlzCD/cyBxh8hMr+ZelhO4qZaPI6pLdWYU=,tag:pFNmcSKy5sR/fOBjyMLMMg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:NMkVihqXZbqKLjNUxRIX,iv:dA6nqyI5YsD5M5eqHsN54NazLIngH9xLn2+vdNHpyno=,tag:uRXEr2hpV7KDV/w9dr3v0w==,type:str]
    namespace: ENC[AES256_GCM,data:YlNvbnYhMwuwsmk=,iv:lCDWexSudpYhSw+zxZwm2PgTuIKHj9jfNfUwkg2y0Yw=,tag:xukBqROyJrZ3izYDy+iyQw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hrfr2t7yq/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-03-12T02:09:49Z"
          enc: CiQAKi+prrZKExvhwluF1GhmkFB4R1IfGDSLajfy5XGAdxuWI4cSSQCn003SzFz4wgz7i+k/ttX+g3whnEiH+jTbaB0ycIVts4lc5YBoUh02UEuNKhi1hQW/aycng8JDhNvsaX/3OlidodBicWzbX8M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-12T02:09:49Z"
    mac: ENC[AES256_GCM,data:wUFuxGWyEevoa2UiCMVtqtS4PfIakOv8zRVyo+E5A10UE6fHNNFptk18Pnq5P0qVAVaqQfWbrr374BnME1teF/frkNBKHiNMEdGj6cCNXLnuZsheWUdbpo6EeJn0Ydag1av4xog7xWQpWzrXwHw4MiGXuZd9ckFi143eC4I1fV4=,iv:tyusKGyQ/WQ8SWpzwPODae9dr7/TTz7o3RqCZZu+QhY=,tag:eQ0eMiFxPhO2zWvrGLoX7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
