#  ___| | __ _  ___| | __
# / __| |/ _` |/ __| |/ /
# \__ \ | (_| | (__|   <
# |___/_|\__,_|\___|_|\_\
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack-bot
  namespace: flux-system
spec:
  type: slack
  channel: dhis2-alerts
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: slack
  namespace: flux-system
spec:
  summary: "Notifications for flux reconciliations"
  eventMetadata:
    cluster: "gke_phx-01h28kjpmp42v8xh59v0qvfpxa_northamerica-northeast1_dhis2-cluster"
    region: "northamerica-northeast1"
  providerRef:
    name: slack-bot
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
  exclusionList:
    - "^Dependencies.*"