apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issuers.yaml
patches:     
- target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt
  patch: |-
    - op: add
      path: /spec/acme/solvers/-
      value:
        selector: {}
        dns01:
          cloudDNS:
            project: pht-01hrfr2t7yq
            hostedZoneName: "beta-phac-aspc-gc-ca"

- target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt
    namespace: istio-system
  patch: |-
    - op: add
      path: /spec/acme/email
      value: simardeep.singh@phac-aspc.gc.ca