apiVersion: v1
kind: ServiceAccount
metadata:
  name: dhis2-sa
  namespace: dhis2
  annotations:
    iam.gke.io/gcp-service-account: dhis2-deployment@phx-01h28kjpmp42v8xh59v0qvfpxa.iam.gserviceaccount.com
