apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: cloudtrace
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/pht-01hrfr2t7yq
  resourceID: cloudtrace.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: cloudkms
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/pht-01hrfr2t7yq
  resourceID: cloudkms.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: cloudresourcemanager
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/pht-01hrfr2t7yq
  resourceID: cloudresourcemanager.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: secretmanager
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/pht-01hrfr2t7yq
  resourceID: secretmanager.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: containersecurity
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/pht-01hrfr2t7yq
  resourceID: containersecurity.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: networkmanagement
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/pht-01hrfr2t7yq
  resourceID: networkmanagement.googleapis.com
