apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique
  name: dhis2-postgis-backup-pht-01hrfr2t7yq
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: northamerica-northeast1
  versioning:
    enabled: true
  storageClass: STANDARD
  uniformBucketLevelAccess: true
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique
  name: dhis2-test-coverage-reports-pht-01hrfr2t7yq
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: northamerica-northeast1
  versioning:
    enabled: true
  storageClass: STANDARD
  uniformBucketLevelAccess: true