apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: dns01-solver
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  displayName: dns01-solver
  description: To complete DNS01 Challenge for cert-manager
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: dhis2-postgis-backup
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  displayName: dhis2-postgis-backup
  description: To backup cloudnative postgis in a gcp bucket
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: sops-kms
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  displayName: sops-kms
  description: To decrypt secrets within flux kustomize controller
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: dhis2-deployment
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  displayName: dhis2-deployment
  description: To assign cloud permissions for DHIS2 deployment in GKE